### ISSUE TITLE
what's the  meaning of _gt_?

### ISSUE THREAD

**Issue by cx1202** [dmoltisanti/air-cvpr23#1]
In the csv file generated by running the code, what specifically is the _gt_ in indicator test_no_act_gt_map_w？

**Comment by dmoltisanti** [comment]
Hi, `no_act_gt` indicates results obtained without using the action class ground truth during inference. These results are reported in Table 3 in the paper. Hope this helps!

**Comment by cx1202** [comment]
> Hi, `no_act_gt` indicates results obtained without using the action class ground truth during inference. These results are reported in Table 3 in the paper. Hope this helps!

Thank you!
